### Create payment
POST http://localhost:8082/payments
Content-Type: application/json
Merchant-Id: 019fbd1b-8e69-74f7-89d4-a2d92ba75a70
Idempotency-Key: {{$guid}}

{ 
    "card_token": "XXXX",
    "card_last4": "1234",
    "card_brand": "visa",
    "amount_cents": 100
 }

### Create payment — merchant inexistente (422)
POST http://localhost:8082/payments
Content-Type: application/json
Merchant-Id: {{$uuid}}
Idempotency-Key: {{$guid}}

{ 
    "card_token": "XXXXXX",
    "card_last4": "1234",
    "card_brand": "visa",
    "amount_cents": 100
}

### Create payment — empty merchant-id header (400)
POST http://localhost:8082/payments
Content-Type: application/json

{ 
    "card_token": "XXXXXX",
    "card_last4": "1234",
    "card_brand": "visa",
    "amount_cents": 100
}

### Create payment — not uuid merchant-id header (400)
POST http://localhost:8082/payments
Content-Type: application/json
Merchant-Id: XXX

{ 
    "card_token": "XXXXXX",
    "card_last4": "1234",
    "card_brand": "visa",
    "amount_cents": 100
}

### Create payment — replay (rodar 2×, esperar 201 IDÊNTICO)
POST http://localhost:8082/payments
Content-Type: application/json
Merchant-Id: 019fbd1b-8e69-74f7-89d4-a2d92ba75a70
Idempotency-Key: 019fdbe9-9298-70dc-a186-e42953c1bc57

{
  "card_token": "XXXXXX",
  "card_last4": "1234",
  "card_brand": "visa",
  "amount_cents": 100
}

### Create payment — mesma key, corpo diferente (422)
POST http://localhost:8082/payments
Content-Type: application/json
Merchant-Id: 019fbd1b-8e69-74f7-89d4-a2d92ba75a70
Idempotency-Key: 019fdbe9-9298-70dc-a186-e42953c1bc57

{
  "card_token": "XXXXXX",
  "card_last4": "1234",
  "card_brand": "visa",
  "amount_cents": 999
}