// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency_keys.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :exec
INSERT INTO idempotency_keys 
(
    idempotency_key, 
    merchant_id, 
    idempotency_operation, 
    request_hash,
    created_at
) 
VALUES ($1, $2, $3, $4, $5)
`

type CreateIdempotencyKeyParams struct {
	IdempotencyKey       string
	MerchantID           uuid.UUID
	IdempotencyOperation string
	RequestHash          string
	CreatedAt            time.Time
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, createIdempotencyKey,
		arg.IdempotencyKey,
		arg.MerchantID,
		arg.IdempotencyOperation,
		arg.RequestHash,
		arg.CreatedAt,
	)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT
    idempotency_key, 
    merchant_id, 
    payment_id,
    idempotency_operation, 
    request_hash,
    response_status,
    response,
    created_at
FROM
    idempotency_keys
WHERE   
    idempotency_key=$1 AND 
    merchant_id=$2
`

type GetIdempotencyKeyParams struct {
	IdempotencyKey string
	MerchantID     uuid.UUID
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.IdempotencyKey, arg.MerchantID)
	var i IdempotencyKey
	err := row.Scan(
		&i.IdempotencyKey,
		&i.MerchantID,
		&i.PaymentID,
		&i.IdempotencyOperation,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const updateIdempotencyKeyPaymentID = `-- name: UpdateIdempotencyKeyPaymentID :exec
UPDATE
    idempotency_keys
SET
    payment_id=$1
WHERE
    idempotency_key=$2 AND 
    merchant_id=$3
`

type UpdateIdempotencyKeyPaymentIDParams struct {
	PaymentID      uuid.NullUUID
	IdempotencyKey string
	MerchantID     uuid.UUID
}

func (q *Queries) UpdateIdempotencyKeyPaymentID(ctx context.Context, arg UpdateIdempotencyKeyPaymentIDParams) error {
	_, err := q.db.Exec(ctx, updateIdempotencyKeyPaymentID, arg.PaymentID, arg.IdempotencyKey, arg.MerchantID)
	return err
}

const updateIdempotencyKeyResponse = `-- name: UpdateIdempotencyKeyResponse :exec
UPDATE
    idempotency_keys
SET
    response_status=$1,
    response=$2
WHERE
    idempotency_key=$3 AND 
    merchant_id=$4
`

type UpdateIdempotencyKeyResponseParams struct {
	ResponseStatus pgtype.Int4
	Response       []byte
	IdempotencyKey string
	MerchantID     uuid.UUID
}

func (q *Queries) UpdateIdempotencyKeyResponse(ctx context.Context, arg UpdateIdempotencyKeyResponseParams) error {
	_, err := q.db.Exec(ctx, updateIdempotencyKeyResponse,
		arg.ResponseStatus,
		arg.Response,
		arg.IdempotencyKey,
		arg.MerchantID,
	)
	return err
}
