// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (id, name, fee_bps, created_at) 
VALUES ($1, $2, $3, $4)
RETURNING id, name, fee_bps, created_at
`

type CreateMerchantParams struct {
	ID        uuid.UUID
	Name      string
	FeeBps    int32
	CreatedAt time.Time
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant,
		arg.ID,
		arg.Name,
		arg.FeeBps,
		arg.CreatedAt,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FeeBps,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchant = `-- name: GetMerchant :one
SELECT 
    id,
    name,
    fee_bps,
    created_at
FROM    
    merchants
WHERE   
    merchants.id=$1
`

func (q *Queries) GetMerchant(ctx context.Context, id uuid.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchant, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FeeBps,
		&i.CreatedAt,
	)
	return i, err
}
