// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID          uuid.UUID
	AccountType string
	MerchantID  uuid.NullUUID
	CreatedAt   time.Time
	Currency    string
}

type IdempotencyKey struct {
	IdempotencyKey       string
	MerchantID           uuid.UUID
	PaymentID            uuid.UUID
	IdempotencyOperation string
	RequestHash          string
	ResponseStatus       int32
	Response             []byte
	CreatedAt            time.Time
}

type LedgerEntry struct {
	ID           uuid.UUID
	PaymentID    uuid.UUID
	AccountID    uuid.UUID
	EntryType    string
	MovementType string
	Amount       int64
	CreatedAt    time.Time
}

type Merchant struct {
	ID        uuid.UUID
	Name      string
	FeeBps    int32
	CreatedAt time.Time
}

type Outbox struct {
	ID          uuid.UUID
	PaymentID   uuid.UUID
	Routing     string
	Message     []byte
	PublishedAt sql.NullTime
	CreatedAt   time.Time
}

type Payment struct {
	ID         uuid.UUID
	MerchantID uuid.UUID
	Status     string
	CreatedAt  time.Time
	Amount     int64
	Currency   string
	CardToken  string
	CardLast4  string
	CardBrand  string
}

type PaymentEvent struct {
	ID           uuid.UUID
	PaymentID    uuid.UUID
	FromStatus   string
	ToStatus     string
	EventType    string
	EventDetails []byte
	CreatedAt    time.Time
}
