// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments 
(
    id, 
    merchant_id, 
    status, 
    created_at,
    amount,
    currency,
    card_token,
    card_last4,
    card_brand
) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, merchant_id, status, created_at, amount, currency, card_token, card_last4, card_brand
`

type CreatePaymentParams struct {
	ID         uuid.UUID
	MerchantID uuid.UUID
	Status     string
	CreatedAt  time.Time
	Amount     int64
	Currency   string
	CardToken  string
	CardLast4  string
	CardBrand  string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.MerchantID,
		arg.Status,
		arg.CreatedAt,
		arg.Amount,
		arg.Currency,
		arg.CardToken,
		arg.CardLast4,
		arg.CardBrand,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Status,
		&i.CreatedAt,
		&i.Amount,
		&i.Currency,
		&i.CardToken,
		&i.CardLast4,
		&i.CardBrand,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT
    id, 
    merchant_id, 
    status, 
    created_at,
    amount,
    currency,
    card_token,
    card_last4,
    card_brand
FROM
    payments
WHERE   
    id=$1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Status,
		&i.CreatedAt,
		&i.Amount,
		&i.Currency,
		&i.CardToken,
		&i.CardLast4,
		&i.CardBrand,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments SET status=$1 WHERE id=$2
`

type UpdatePaymentStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus, arg.Status, arg.ID)
	return err
}
