// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPaymentEvent = `-- name: CreatePaymentEvent :exec
INSERT INTO payment_events
(
    id, 
    payment_id, 
    from_status, 
    to_status,
    event_type,
    event_details,
    created_at
) 
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePaymentEventParams struct {
	ID           uuid.UUID
	PaymentID    uuid.UUID
	FromStatus   string
	ToStatus     string
	EventType    string
	EventDetails []byte
	CreatedAt    time.Time
}

func (q *Queries) CreatePaymentEvent(ctx context.Context, arg CreatePaymentEventParams) error {
	_, err := q.db.Exec(ctx, createPaymentEvent,
		arg.ID,
		arg.PaymentID,
		arg.FromStatus,
		arg.ToStatus,
		arg.EventType,
		arg.EventDetails,
		arg.CreatedAt,
	)
	return err
}
